// Auto-generated by scripts/generate-patterns.ts - DO NOT EDIT MANUALLY
// Generated: 2025-12-29T13:15:04.787Z
// Total patterns: 168

import type { Pattern } from "../schema";

import { activeActive } from "./active-active";
import { activePassive } from "./active-passive";
import { actorModel } from "./actor-model";
import { adaptiveConcurrency } from "./adaptive-concurrency";
import { adaptiveThresholds } from "./adaptive-thresholds";
import { aging } from "./aging";
import { approximation } from "./approximation";
import { asyncAwait } from "./async-await";
import { bTreeIndex } from "./b-tree-index";
import { backpressure } from "./backpressure";
import { backtracking } from "./backtracking";
import { backupRestore } from "./backup-restore";
import { batching } from "./batching";
import { bitmapIndex } from "./bitmap-index";
import { bloomFilters } from "./bloom-filters";
import { bulkOperations } from "./bulk-operations";
import { bulkhead } from "./bulkhead";
import { cacheAside } from "./cache-aside";
import { circuitBreaker } from "./circuit-breaker";
import { closedState } from "./closed-state";
import { coalescing } from "./coalescing";
import { compositeIndex } from "./composite-index";
import { compression } from "./compression";
import { connectionPoolIsolation } from "./connection-pool-isolation";
import { connectionPooling } from "./connection-pooling";
import { connectionTimeout } from "./connection-timeout";
import { consistentHashing } from "./consistent-hashing";
import { contractTesting } from "./contract-testing";
import { cooperativeYielding } from "./cooperative-yielding";
import { coordinatedCheckpoint } from "./coordinated-checkpoint";
import { copyOnWrite } from "./copy-on-write";
import { dataLoader as dataloader } from "./dataloader";
import { deadlinePropagation } from "./deadline-propagation";
import { deadlineScheduling } from "./deadline-scheduling";
import { debouncing } from "./debouncing";
import { dedupQueue } from "./dedup-queue";
import { deltaEncoding } from "./delta-encoding";
import { dependencyInjection } from "./dependency-injection";
import { dictionaryCoding } from "./dictionary-coding";
import { directoryBased } from "./directory-based";
import { divideAndConquer } from "./divide-and-conquer";
import { dockerSwarm } from "./docker-swarm";
import { dynamicProgramming } from "./dynamic-programming";
import { e2EEncryption as e2eEncryption } from "./e2e-encryption";
import { eCSFargate as ecsFargate } from "./ecs-fargate";
import { encryptionAtRest } from "./encryption-at-rest";
import { envelopeEncryption } from "./envelope-encryption";
import { exactlyOnceDelivery } from "./exactly-once-delivery";
import { exponentialBackoff } from "./exponential-backoff";
import { fixedInterval } from "./fixed-interval";
import { flyweight } from "./flyweight";
import { forkJoin } from "./fork-join";
import { geographicSharding } from "./geographic-sharding";
import { graphite } from "./graphite";
import { graphs } from "./graphs";
import { greedy } from "./greedy";
import { halfOpenState } from "./half-open-state";
import { hashIndex } from "./hash-index";
import { hashRing } from "./hash-ring";
import { hashSharding } from "./hash-sharding";
import { hashTables } from "./hash-tables";
import { heaps } from "./heaps";
import { idempotency } from "./idempotency";
import { incrementalCheckpoint } from "./incremental-checkpoint";
import { influxDB as influxdb } from "./influxdb";
import { invertedIndex } from "./inverted-index";
import { iPHash as ipHash } from "./ip-hash";
import { jaeger } from "./jaeger";
import { jitter } from "./jitter";
import { jumpHash } from "./jump-hash";
import { jWT as jwt } from "./jwt";
import { keyRotation } from "./key-rotation";
import { kubernetes } from "./kubernetes";
import { lazyInitialization } from "./lazy-initialization";
import { lazyLoading } from "./lazy-loading";
import { leaderFollower } from "./leader-follower";
import { leaderless } from "./leaderless";
import { leakyBucket } from "./leaky-bucket";
import { leastConnections } from "./least-connections";
import { logStructured } from "./log-structured";
import { logicalLogging } from "./logical-logging";
import { lossless } from "./lossless";
import { lossy } from "./lossy";
import { lotteryScheduling } from "./lottery-scheduling";
import { maxMinFairness } from "./max-min-fairness";
import { memoization } from "./memoization";
import { microBatching } from "./micro-batching";
import { microFrontends } from "./micro-frontends";
import { microservices } from "./microservices";
import { mocking } from "./mocking";
import { modularMonolith } from "./modular-monolith";
import { multiLeader } from "./multi-leader";
import { multiLevelQueue } from "./multi-level-queue";
import { multiThreading } from "./multi-threading";
import { nagleSAlgorithm } from "./nagle-s-algorithm"; // Correctly exported
import { nomad } from "./nomad";
import { oAuth20 as oauth20 } from "./oauth-2-0";
import { objectPooling } from "./object-pooling";
import { oIDC as oidc } from "./oidc";
import { openState } from "./open-state";
import { openTelemetry as opentelemetry } from "./opentelemetry";
import { pagination } from "./pagination";
import { periodicCheckpoint } from "./periodic-checkpoint";
import { physicalLogging } from "./physical-logging";
import { physiologicalLogging } from "./physiological-logging";
import { pilotLight } from "./pilot-light";
import { pluginArchitecture } from "./plugin-architecture";
import { prefetching } from "./prefetching";
import { priorityPreemption } from "./priority-preemption";
import { priorityQueue } from "./priority-queue";
import { processIsolation } from "./process-isolation";
import { prometheus } from "./prometheus";
import { propertyBasedTesting } from "./property-based-testing";
import { protocolBuffers } from "./protocol-buffers";
import { rWN } from "./r-w-n"; // Correctly exported as rWN
import { random } from "./random";
import { rangeSharding } from "./range-sharding";
import { rateLimiting } from "./rate-limiting";
import { readQuorum } from "./read-quorum";
import { readReplicas } from "./read-replicas";
import { readThrough } from "./read-through";
import { readTimeout } from "./read-timeout";
import { rEDMethod as redMethod } from "./red-method";
import { refreshAhead } from "./refresh-ahead";
import { refreshTokens } from "./refresh-tokens";
import { rendezvousHashing } from "./rendezvous-hashing";
import { requestTimeout } from "./request-timeout";
import { retry } from "./retry";
import { retryBudget } from "./retry-budget";
import { roundRobin } from "./round-robin";
import { runLengthEncoding } from "./run-length-encoding";
import { sAML as saml } from "./saml";
import { sampling } from "./sampling";
import { serverIsolation } from "./server-isolation";
import { sharedLibraries } from "./shared-libraries";
import { shortestJobFirst } from "./shortest-job-first";
import { sIMD as simd } from "./simd";
import { simpleMajority } from "./simple-majority";
import { singleflight } from "./singleflight";
import { skipLists } from "./skip-lists";
import { spatialIndex } from "./spatial-index";
import { statsD as statsd } from "./statsd";
import { streaming } from "./streaming";
import { stringInterning } from "./string-interning";
import { tempo } from "./tempo";
import { testFixtures } from "./test-fixtures";
import { threadPoolIsolation } from "./thread-pool-isolation";
import { threadPooling } from "./thread-pooling";
import { throttling } from "./throttling";
import { timeSlicing } from "./time-slicing";
import { timeout } from "./timeout";
import { tLSSSL as tlsSsl } from "./tls-ssl";
import { tokenBucket } from "./token-bucket";
import { transactionCheckpoint } from "./transaction-checkpoint";
import { trees } from "./trees";
import { uSEMethod as useMethod } from "./use-method";
import { virtualScrolling } from "./virtual-scrolling";
import { weighted } from "./weighted";
import { weightedFairQueuing } from "./weighted-fair-queuing";
import { windowing } from "./windowing";
import { workerPools } from "./worker-pools";
import { writeBack } from "./write-back";
import { writeBuffering } from "./write-buffering";
import { writeQuorum } from "./write-quorum";
import { writeThrough } from "./write-through";
import { writeTimeout } from "./write-timeout";
import { xRay } from "./x-ray"; // Correctly exported as xRay
import { zipkin } from "./zipkin";

export { activeActive };
export { activePassive };
export { actorModel };
export { adaptiveConcurrency };
export { adaptiveThresholds };
export { aging };
export { approximation };
export { asyncAwait };
export { bTreeIndex };
export { backpressure };
export { backtracking };
export { backupRestore };
export { batching };
export { bitmapIndex };
export { bloomFilters };
export { bulkOperations };
export { bulkhead };
export { cacheAside };
export { circuitBreaker };
export { closedState };
export { coalescing };
export { compositeIndex };
export { compression };
export { connectionPoolIsolation };
export { connectionPooling };
export { connectionTimeout };
export { consistentHashing };
export { contractTesting };
export { cooperativeYielding };
export { coordinatedCheckpoint };
export { copyOnWrite };
export { dataloader };
export { deadlinePropagation };
export { deadlineScheduling };
export { debouncing };
export { dedupQueue };
export { deltaEncoding };
export { dependencyInjection };
export { dictionaryCoding };
export { directoryBased };
export { divideAndConquer };
export { dockerSwarm };
export { dynamicProgramming };
export { e2eEncryption };
export { ecsFargate };
export { encryptionAtRest };
export { envelopeEncryption };
export { exactlyOnceDelivery };
export { exponentialBackoff };
export { fixedInterval };
export { flyweight };
export { forkJoin };
export { geographicSharding };
export { graphite };
export { graphs };
export { greedy };
export { halfOpenState };
export { hashIndex };
export { hashRing };
export { hashSharding };
export { hashTables };
export { heaps };
export { idempotency };
export { incrementalCheckpoint };
export { influxdb };
export { invertedIndex };
export { ipHash };
export { jaeger };
export { jitter };
export { jumpHash };
export { jwt };
export { keyRotation };
export { kubernetes };
export { lazyInitialization };
export { lazyLoading };
export { leaderFollower };
export { leaderless };
export { leakyBucket };
export { leastConnections };
export { logStructured };
export { logicalLogging };
export { lossless };
export { lossy };
export { lotteryScheduling };
export { maxMinFairness };
export { memoization };
export { microBatching };
export { microFrontends };
export { microservices };
export { mocking };
export { modularMonolith };
export { multiLeader };
export { multiLevelQueue };
export { multiThreading };
export { nagleSAlgorithm };
export { nomad };
export { oauth20 };
export { objectPooling };
export { oidc };
export { openState };
export { opentelemetry };
export { pagination };
export { periodicCheckpoint };
export { physicalLogging };
export { physiologicalLogging };
export { pilotLight };
export { pluginArchitecture };
export { prefetching };
export { priorityPreemption };
export { priorityQueue };
export { processIsolation };
export { prometheus };
export { propertyBasedTesting };
export { protocolBuffers };
export { rWN };
export { random };
export { rangeSharding };
export { rateLimiting };
export { readQuorum };
export { readReplicas };
export { readThrough };
export { readTimeout };
export { redMethod };
export { refreshAhead };
export { refreshTokens };
export { rendezvousHashing };
export { requestTimeout };
export { retry };
export { retryBudget };
export { roundRobin };
export { runLengthEncoding };
export { saml };
export { sampling };
export { serverIsolation };
export { sharedLibraries };
export { shortestJobFirst };
export { simd };
export { simpleMajority };
export { singleflight };
export { skipLists };
export { spatialIndex };
export { statsd };
export { streaming };
export { stringInterning };
export { tempo };
export { testFixtures };
export { threadPoolIsolation };
export { threadPooling };
export { throttling };
export { timeSlicing };
export { timeout };
export { tlsSsl };
export { tokenBucket };
export { transactionCheckpoint };
export { trees };
export { useMethod };
export { virtualScrolling };
export { weighted };
export { weightedFairQueuing };
export { windowing };
export { workerPools };
export { writeBack };
export { writeBuffering };
export { writeQuorum };
export { writeThrough };
export { writeTimeout };
export { xRay };
export { zipkin };

export const patterns: Record<string, Pattern> = {
  "active-active": activeActive,
  "active-passive": activePassive,
  "actor-model": actorModel,
  "adaptive-concurrency": adaptiveConcurrency,
  "adaptive-thresholds": adaptiveThresholds,
  aging: aging,
  approximation: approximation,
  "async-await": asyncAwait,
  "b-tree-index": bTreeIndex,
  backpressure: backpressure,
  backtracking: backtracking,
  "backup-restore": backupRestore,
  batching: batching,
  "bitmap-index": bitmapIndex,
  "bloom-filters": bloomFilters,
  "bulk-operations": bulkOperations,
  bulkhead: bulkhead,
  "cache-aside": cacheAside,
  "circuit-breaker": circuitBreaker,
  "closed-state": closedState,
  coalescing: coalescing,
  "composite-index": compositeIndex,
  compression: compression,
  "connection-pool-isolation": connectionPoolIsolation,
  "connection-pooling": connectionPooling,
  "connection-timeout": connectionTimeout,
  "consistent-hashing": consistentHashing,
  "contract-testing": contractTesting,
  "cooperative-yielding": cooperativeYielding,
  "coordinated-checkpoint": coordinatedCheckpoint,
  "copy-on-write": copyOnWrite,
  dataloader: dataloader,
  "deadline-propagation": deadlinePropagation,
  "deadline-scheduling": deadlineScheduling,
  debouncing: debouncing,
  "dedup-queue": dedupQueue,
  "delta-encoding": deltaEncoding,
  "dependency-injection": dependencyInjection,
  "dictionary-coding": dictionaryCoding,
  "directory-based": directoryBased,
  "divide-and-conquer": divideAndConquer,
  "docker-swarm": dockerSwarm,
  "dynamic-programming": dynamicProgramming,
  "e2e-encryption": e2eEncryption,
  "ecs-fargate": ecsFargate,
  "encryption-at-rest": encryptionAtRest,
  "envelope-encryption": envelopeEncryption,
  "exactly-once-delivery": exactlyOnceDelivery,
  "exponential-backoff": exponentialBackoff,
  "fixed-interval": fixedInterval,
  flyweight: flyweight,
  "fork-join": forkJoin,
  "geographic-sharding": geographicSharding,
  graphite: graphite,
  graphs: graphs,
  greedy: greedy,
  "half-open-state": halfOpenState,
  "hash-index": hashIndex,
  "hash-ring": hashRing,
  "hash-sharding": hashSharding,
  "hash-tables": hashTables,
  heaps: heaps,
  idempotency: idempotency,
  "incremental-checkpoint": incrementalCheckpoint,
  influxdb: influxdb,
  "inverted-index": invertedIndex,
  "ip-hash": ipHash,
  jaeger: jaeger,
  jitter: jitter,
  "jump-hash": jumpHash,
  jwt: jwt,
  "key-rotation": keyRotation,
  kubernetes: kubernetes,
  "lazy-initialization": lazyInitialization,
  "lazy-loading": lazyLoading,
  "leader-follower": leaderFollower,
  leaderless: leaderless,
  "leaky-bucket": leakyBucket,
  "least-connections": leastConnections,
  "log-structured": logStructured,
  "logical-logging": logicalLogging,
  lossless: lossless,
  lossy: lossy,
  "lottery-scheduling": lotteryScheduling,
  "max-min-fairness": maxMinFairness,
  memoization: memoization,
  "micro-batching": microBatching,
  "micro-frontends": microFrontends,
  microservices: microservices,
  mocking: mocking,
  "modular-monolith": modularMonolith,
  "multi-leader": multiLeader,
  "multi-level-queue": multiLevelQueue,
  "multi-threading": multiThreading,
  "nagle-s-algorithm": nagleSAlgorithm,
  nomad: nomad,
  "oauth-2-0": oauth20,
  "object-pooling": objectPooling,
  oidc: oidc,
  "open-state": openState,
  opentelemetry: opentelemetry,
  pagination: pagination,
  "periodic-checkpoint": periodicCheckpoint,
  "physical-logging": physicalLogging,
  "physiological-logging": physiologicalLogging,
  "pilot-light": pilotLight,
  "plugin-architecture": pluginArchitecture,
  prefetching: prefetching,
  "priority-preemption": priorityPreemption,
  "priority-queue": priorityQueue,
  "process-isolation": processIsolation,
  prometheus: prometheus,
  "property-based-testing": propertyBasedTesting,
  "protocol-buffers": protocolBuffers,
  "r-w-n": rWN,
  random: random,
  "range-sharding": rangeSharding,
  "rate-limiting": rateLimiting,
  "read-quorum": readQuorum,
  "read-replicas": readReplicas,
  "read-through": readThrough,
  "read-timeout": readTimeout,
  "red-method": redMethod,
  "refresh-ahead": refreshAhead,
  "refresh-tokens": refreshTokens,
  "rendezvous-hashing": rendezvousHashing,
  "request-timeout": requestTimeout,
  retry: retry,
  "retry-budget": retryBudget,
  "round-robin": roundRobin,
  "run-length-encoding": runLengthEncoding,
  saml: saml,
  sampling: sampling,
  "server-isolation": serverIsolation,
  "shared-libraries": sharedLibraries,
  "shortest-job-first": shortestJobFirst,
  simd: simd,
  "simple-majority": simpleMajority,
  singleflight: singleflight,
  "skip-lists": skipLists,
  "spatial-index": spatialIndex,
  statsd: statsd,
  streaming: streaming,
  "string-interning": stringInterning,
  tempo: tempo,
  "test-fixtures": testFixtures,
  "thread-pool-isolation": threadPoolIsolation,
  "thread-pooling": threadPooling,
  throttling: throttling,
  "time-slicing": timeSlicing,
  timeout: timeout,
  "tls-ssl": tlsSsl,
  "token-bucket": tokenBucket,
  "transaction-checkpoint": transactionCheckpoint,
  trees: trees,
  "use-method": useMethod,
  "virtual-scrolling": virtualScrolling,
  weighted: weighted,
  "weighted-fair-queuing": weightedFairQueuing,
  windowing: windowing,
  "worker-pools": workerPools,
  "write-back": writeBack,
  "write-buffering": writeBuffering,
  "write-quorum": writeQuorum,
  "write-through": writeThrough,
  "write-timeout": writeTimeout,
  "x-ray": xRay,
  zipkin: zipkin,
};

export const patternList: Pattern[] = Object.values(patterns);
