#!/usr/bin/env tsx
/**
 * Pattern File Generator
 *
 * Reads corpus-manifest.json and generates pattern files for all Level 4 patterns.
 * Creates scaffold with corpus metadata and TODO stubs for incremental completion.
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface CorpusPattern {
  name: string;
  emoji: string;
  tagline: string;
  corpusPath: string;
  lineNumber: number;
  hierarchy: {
    quality: string;
    strategy: string;
    family: string;
    level: 4;
  };
}

function toKebabCase(str: string): string {
  // Remove parentheses and their contents first
  const withoutParens = str.replace(/\([^)]*\)/g, "");
  return withoutParens
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function toCamelCase(str: string): string {
  // Remove parentheses and their contents first
  const withoutParens = str.replace(/\([^)]*\)/g, "");
  return withoutParens
    .trim()
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^[A-Z]/, (chr) => chr.toLowerCase());
}

function generatePatternFile(pattern: CorpusPattern): string {
  const id = toKebabCase(pattern.name);
  const varName = toCamelCase(pattern.name);

  return `import type { Pattern } from "../schema";

export const ${varName}: Pattern = {
  id: "${id}",
  slug: "${id}",
  corpusPath: "${pattern.corpusPath}",

  hierarchy: {
    quality: "${pattern.hierarchy.quality}",
    strategy: "${pattern.hierarchy.strategy}",
    family: "${pattern.hierarchy.family}",
    level: 4,
  },

  concept: {
    name: "${pattern.name}",
    emoji: "${pattern.emoji}",
    tagline: "${pattern.tagline}",
    definition: "TODO: Expand from corpus tagline and add comprehensive definition",
    problemSolved: "TODO: What problem does this pattern solve?",
    tradeoffs: {
      pros: [
        "TODO: List advantages of this pattern",
      ],
      cons: [
        "TODO: List drawbacks and limitations",
      ],
    },
    relatedPatterns: [], // TODO: Find related patterns in same family
  },

  structure: {
    participants: [
      {
        name: "TODO: Participant name",
        role: "TODO: Participant role",
        responsibilities: [
          "TODO: Responsibility 1",
          "TODO: Responsibility 2",
        ],
      },
    ],
    diagram: \`graph TB
    Start([Start]) --> Action[TODO: Add Mermaid diagram]
    Action --> End([End])

    style Start fill:#e1f5e1
    style End fill:#e1f5e1\`,
    flow: [
      {
        step: 1,
        actor: "TODO: Actor name",
        action: "TODO: Action",
        description: "TODO: Description",
      },
    ],
    invariants: [
      "TODO: List pattern invariants and constraints",
    ],
  },

  codeExamples: [
    {
      id: "${id}-ts-basic",
      language: "typescript",
      title: "TODO: ${pattern.name} Implementation",
      description: "TODO: Describe the code example",
      code: \`// TODO: Add runnable TypeScript example for ${pattern.name}
// This should demonstrate the core concept of the pattern

function example() {
  // Implementation here
}\`,
    },
  ],
};
`;
}

function getAllPatternFiles(patternsDir: string): string[] {
  const files = fs.readdirSync(patternsDir);
  return files
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .map((f) => f.replace(/\.ts$/, ""));
}

function generateIndexFile(
  patterns: CorpusPattern[],
  patternsDir: string,
): string {
  // Get all pattern files that exist
  const allPatternFiles = getAllPatternFiles(patternsDir);

  const imports: string[] = [];
  const exports: string[] = [];
  const recordEntries: string[] = [];

  // Sort for consistent output
  allPatternFiles.sort().forEach((fileId) => {
    const varName = toCamelCase(fileId);
    imports.push(`import { ${varName} } from "./${fileId}";`);
    exports.push(`export { ${varName} };`);
    recordEntries.push(`  "${fileId}": ${varName},`);
  });

  return `// Auto-generated by scripts/generate-patterns.ts - DO NOT EDIT MANUALLY
// Generated: ${new Date().toISOString()}
// Total patterns: ${allPatternFiles.length}

import type { Pattern } from "../schema";

${imports.join("\n")}

${exports.join("\n")}

export const patterns: Record<string, Pattern> = {
${recordEntries.join("\n")}
};

export const patternList: Pattern[] = Object.values(patterns);
`;
}

function main() {
  const manifestPath = path.join(__dirname, "../corpus-manifest.json");
  const patternsDir = path.join(__dirname, "../src/data/patterns");

  console.log("📖 Reading corpus manifest...");
  const patterns: CorpusPattern[] = JSON.parse(
    fs.readFileSync(manifestPath, "utf-8"),
  );

  console.log(`✅ Loaded ${patterns.length} patterns\n`);

  // Create patterns directory if it doesn't exist
  if (!fs.existsSync(patternsDir)) {
    fs.mkdirSync(patternsDir, { recursive: true });
  }

  console.log("🏗️  Generating pattern files...");

  let created = 0;
  let skipped = 0;

  patterns.forEach((pattern) => {
    const id = toKebabCase(pattern.name);
    const filePath = path.join(patternsDir, `${id}.ts`);

    // Skip if file already exists (don't overwrite manually created patterns)
    if (fs.existsSync(filePath)) {
      skipped++;
      return;
    }

    const content = generatePatternFile(pattern);
    fs.writeFileSync(filePath, content);
    created++;
  });

  console.log(`   ✅ Created: ${created} files`);
  console.log(`   ⏭️  Skipped: ${skipped} files (already exist)\n`);

  // Generate index.ts
  console.log("📦 Generating index.ts...");
  const indexPath = path.join(patternsDir, "index.ts");
  const indexContent = generateIndexFile(patterns, patternsDir);
  fs.writeFileSync(indexPath, indexContent);
  console.log(`   ✅ Generated: ${indexPath}\n`);

  console.log(`🎉 Done! Generated ${created} new pattern files`);
  console.log(`\n📊 Summary:`);
  console.log(`   Total patterns in manifest: ${patterns.length}`);
  console.log(`   New files created: ${created}`);
  console.log(`   Existing files preserved: ${skipped}`);
}

main();
